apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-ai-gateway
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/envoyproxy/ai-gateway
    path: manifests/charts/ai-gateway-crds-helm
    targetRevision: v0.4.0
  - repoURL: https://github.com/envoyproxy/ai-gateway
    path: manifests/charts/ai-gateway-helm
    targetRevision: v0.4.0
    helm:
      valueFiles:
      - $VALUES/infra/base/terraform/helm-values/envoy-ai-gateway-values.yaml
  - repoURL: https://github.com/samarsinghal/ai-on-eks
    targetRevision: HEAD
    ref: VALUES
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-ai-gateway-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
